// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQQSJbfGTBlEFiPw1lNv3UMs9knl4oBsw',
    appId: '1:887308707252:web:50805f4b25d1824e9e7ee1',
    messagingSenderId: '887308707252',
    projectId: 'educube-5d268',
    authDomain: 'educube-5d268.firebaseapp.com',
    databaseURL: 'https://educube-5d268.firebaseio.com',
    storageBucket: 'educube-5d268.appspot.com',
    measurementId: 'G-F4BXPJW5F6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD3DpMHgDUrHM_MJBjWcRgRbEC-3VIcyY',
    appId: '1:887308707252:android:9fee504186715a0f',
    messagingSenderId: '887308707252',
    projectId: 'educube-5d268',
    databaseURL: 'https://educube-5d268.firebaseio.com',
    storageBucket: 'educube-5d268.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2B2vSwVgynxoWZHNe8RWje2f_Hg6_4uk',
    appId: '1:887308707252:ios:9fee504186715a0f',
    messagingSenderId: '887308707252',
    projectId: 'educube-5d268',
    databaseURL: 'https://educube-5d268.firebaseio.com',
    storageBucket: 'educube-5d268.appspot.com',
    iosClientId: '887308707252-o7mt5l1b21sn7c56e5m32kofsohtsjaj.apps.googleusercontent.com',
    iosBundleId: 'com.globals.educube.parent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2B2vSwVgynxoWZHNe8RWje2f_Hg6_4uk',
    appId: '1:887308707252:ios:99d2d6db2ea2d5df9e7ee1',
    messagingSenderId: '887308707252',
    projectId: 'educube-5d268',
    databaseURL: 'https://educube-5d268.firebaseio.com',
    storageBucket: 'educube-5d268.appspot.com',
    iosBundleId: 'com.app.educube1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQQSJbfGTBlEFiPw1lNv3UMs9knl4oBsw',
    appId: '1:887308707252:web:c63369d1bc3238309e7ee1',
    messagingSenderId: '887308707252',
    projectId: 'educube-5d268',
    authDomain: 'educube-5d268.firebaseapp.com',
    databaseURL: 'https://educube-5d268.firebaseio.com',
    storageBucket: 'educube-5d268.appspot.com',
    measurementId: 'G-H3DTXRGKCK',
  );
}
